### ISSUE TITLE
Prettier Apex v2 Roadmap

### ISSUE THREAD

**Issue by dangmai** [dangmai/prettier-plugin-apex#900]
I am planning to release the next major version of Prettier Apex right after upstream Prettier releases v3. Here is the checklist of things I'd like to get done before then:

- [x] Support Prettier v3 plugin structure. https://github.com/dangmai/prettier-plugin-apex/issues/673.
- [x] Distribute this library as ESM.
- [x] Remove support for old NodeJS versions. ~~Currently I'm still debating whether to remove NodeJS 16.x yet. It depends on the timing of upstream Prettier release, if it's close to EOL of NodeJS 16.x series I will remove support for it. The main pros for removing support for 16.x is that I can remove `cross-fetch` dependency and use native NodeJS `fetch` instead.~~ I have decided to remove support for NodeJS 16.x series. This major update already requires manual intervention from users anyway, so let's just make it a step in the upgrading process.
- [x] Remove `yargs` dependency.
- [ ] ~~Add Playground and publish to the Internet, so users can quickly format Apex code without installing all the toolchain. This couldn't be done with Prettier v2 because of the synchronous plugin arch, but now it is possible.~~ This will be done after official Prettier Apex v2 is released
  - [x] https://github.com/dangmai/prettier-plugin-apex/pull/901.
  - [x] ~~Move the testing framework to `vite` ecosystem. Jest is increasingly becoming a burden, especially with its poor ESM support.~~ Since we're moving off of NodeJS 16, where the majority of flakiness comes from, I am planning to keep using Jest for the time being.
  - [x] Build standalone UMD package. Currently done with Rollup, will move to Vite instead.
- [x] Migration guide from Prettier Apex v1 to v2: https://github.com/dangmai/prettier-plugin-apex/wiki/Upgrading-to-Prettier-Apex-v2
- [x] Ask Salesforce team to update their documentation.

As of right now, I am not planning on adding any formatting change to this release, so that users can focus on migrating without seeing changes to their formatted code. This may change if critical bugs need to be fixed.

**Comment by dangmai** [comment]
Now that Prettier v3 is officially out, I will release an official version of Prettier Apex v2 in the next couple of days so that users have an upgrade path forward (there is a beta available already that works with Prettier v3 in the mean time).

@pozil could you help me contact Salesforce documentation team to modify the current guide page for Prettier for this release? https://developer.salesforce.com/tools/vscode/en/user-guide/prettier

For Prettier v3, the `.prettierrc` file needs an explicit `plugins` attribute in order for plugins to work, so the `.prettierrc` file in that guide needs to be updated to:

```json
{
  "plugins": ["prettier-plugin-apex"],
  "trailingComma": "none",
  "overrides": [
    {
      "files": "**/lwc/**/*.html",
      "options": { "parser": "lwc" }
    },
    {
      "files": "*.{cmp,page,component}",
      "options": { "parser": "html" }
    }
  ]
}
```

**Comment by dangmai** [comment]
I actually found out that the docs on Salesforce site is open source, and opened a PR to update it here: https://github.com/forcedotcom/salesforcedx-vscode/pull/4961

**Comment by pozil** [comment]
Thanks for your work and for what you bring to the community @dangmai.
